Import

In [ ]:
import numpy as np

Array Creation

In [ ]:
list1=[2,4,3,1]
arr=np.array(list1)
print(arr)

[2 4 3 1]


1-D

In [ ]:
array=np.array([1,2,3,4])
print(array)

[1 2 3 4]


2-D

In [ ]:
array1 = np.array([[1,2,3,4],
 [3,4,5,6]])
print(array1)

[[1 2 3 4]
 [3 4 5 6]]


3-D

In [ ]:
array2 = np.array([[[1,2,3,4],
                 [3,4,5,6],
                 [4,3,2,1]],

                [[2,3,4,5],
                  [3,4,5,6],
                  [4,7,8,9]]])

print(array1)

[[1 2 3 4]
 [3 4 5 6]]


Data Type

In [32]:
array3 = np.array([[1,2,3,4],
 [3,4,5,6]])
print(array3.dtype)

int64


In [33]:
array2 = np.array([[1,2,3,4],
 [3,4,5,6]])
print(array2.dtype)

int64


shape,size,dimensions

In [ ]:
print(array3.shape)
print(array3.size)
print(array3.ndim)

(2, 4)
8
2


itemsize


In [ ]:
array4 = np.array([2,3,4,5])
array5 = np.array([4,5,6,7], dtype=np.int32)
print(array4.itemsize)
print(array5.itemsize)

8
4


In [34]:
array4 = np.array([2,3,4,5])
array5 = np.array([4,5,6,7], dtype=np.int64)
print(array4.itemsize)
print(array5.itemsize)

8
8


In [37]:
import numpy as np

arr7 = np.array([[1,2,3,4]])
print(arr7[0])

[1 2 3 4]


In [18]:
import numpy as np

arr7 = np.array([[1,2,3,4]])
print(arr7[0])


[1 2 3 4]


modify

In [21]:
array[1]=10
print(array)

[ 1 10  3  4]


In [24]:
array = np.array([[9,8,6,5],
                       [0,6,5,45],
                       [2, 4, 6, 8]])
ele1 = array[1, 3]
print("4th Element at 2nd Row:",ele1)
ele2 = array[0, 1]
print("2nd Element at First Row:",ele2)

4th Element at 2nd Row: 45
2nd Element at First Row: 8


median

In [25]:
array1 = np.array([1, 2, 3, 4, 5])
median = np.median(array1)

print(median)

3.0


min

In [26]:
m= np.array([76, 78, 81, 66, 85])
std_m = np.min(m)
print(std_m)

66


max

In [28]:
m = np.array([76, 78, 81, 66, 85])
std_m = np.max(m)
print(std_m)

85


percentail

In [40]:
ms = np.array([98,65,45,34,56,78,12,32,45])
std_ms = np.percentile(ms,50)
print(std_ms)

45.0


In [38]:
ma = np.array([90,87,67,54,76,67,7,88,26])
mean_ma = np.mean(ma)

print(mean_ma)

62.44444444444444
